### ISSUE TITLE
Compatibility issue with the Player.mouseInterface property

### ISSUE THREAD

**Issue by hocha113** [MechanicPluto24/Terraria_Macrocosm#141]
**Issue Description:**
After enabling the mod, the `Player.mouseInterface` property only returns `false` in most update cycles.

**Necessity of Fix:**
Quite necessary. `Player.mouseInterface` is a frequently used property, and many mod interactions depend on it.

**Reproduction Probability:** 100%

**Steps to Reproduce:**
Create a projectile and print the value of `Player.mouseInterface` in its AI method. Summon it in the world. Generally, when the player's mouse is pointing at the inventory menu, the projectile should print `True`, but with MacrocosmMod enabled, this does not happen.

**Example showing this issue:**
![image](https://github.com/user-attachments/assets/5e0b5e48-0776-4800-8e74-a99375d333b5)
*Without MacrocosmMod enabled:*  
![image](https://github.com/user-attachments/assets/e3acafd8-d713-4755-b2f6-90ee6253e110)
*With MacrocosmMod enabled:*  
![image](https://github.com/user-attachments/assets/e3c88c9c-92f7-43d0-a0b8-fe87939c4852)
*Mods enabled during reproduction:*  
![image](https://github.com/user-attachments/assets/ff2077f1-98a2-4ae8-a653-9d1bcbd8f8aa)

This issue also occurs in methods such as `NPC.AI()`, where these hooks should retrieve the correct `Player.mouseInterface` value during execution.

I suspect the problem might be located in `Macrocosm.Common.Players.RocketPlayer.ResetEffects()`, where `Player.mouseInterface` is manually set to `false`, which would block subsequent code from retrieving the correct value.

**Comment by GeorgeFeldy** [comment]
noted, thanks! probably not intended. will look into it

**Comment by GeorgeFeldy** [comment]
![image](https://github.com/user-attachments/assets/85df9cb1-0823-4b86-8f4a-39adaf77da02)
It appears that not only RocketPlayer was the issue, but some bad code in UIInventorySlot

**Comment by hocha113** [comment]
Yes, this issue was fixed very promptly.
